### PR TITLE
Port to python3.

### PR DESCRIPTION
**Pull request by chimosky**
@quozl kindly review.

### CODE REVIEW

**Comment by quozl** [comment]
The activity before porting doesn't seem to work, or I don't know how to use it.  Please provide a test plan, or fix https://github.com/godiard/fototoon-activity/issues/18 first.

**Comment by chimosky** [comment]
Before porting it works fine for me, are there any logs?

**Comment by quozl** [comment]
No logs.  How do you test it?

**Comment by chimosky** [comment]
I didn't have any issues starting it and no logs seems a bit strange.

**Comment by chimosky** [comment]
> The activity before porting doesn't seem to work, or I don't know how to use it. Please provide a test plan, or fix [godiard#18](https://github.com/godiard/fototoon-activity/issues/18) first.

When you say doesn't work, did it not start?.

**Comment by quozl** [comment]
Starting isn't a problem.  Using the activity is where I'm lost.  How did you use it to test it?

**Comment by chimosky** [comment]
When the activity starts up you add images by clicking on the `Choose an image` button in the center of the activity, or by clicking the `Add Photo` button in the toolbar. You rearrange the images by clicking on the `Edit button` and clicking on `Change image order`.
You can also add a globe by using the `Add globe` button.

**Comment by quozl** [comment]
Thanks.  I've established a test method for the current _master_ branch.

d69a61d does work with Python 2.

But when I began to test d69a61d on Python 3, it instantly failed.  The failure suggests you haven't tested.  Please test before commit.

The actual failure relates to [Check for use of Gtk.CssProvider, and if so ensure the load_from_data function is given bytes rather than unicode strings](https://github.com/sugarlabs/sugar-docs/blob/master/src/python-porting-guide.md#how-to-port-an-activity-to-python-3).

**Comment by chimosky** [comment]
> Thanks. I've established a test method for the current _master_ branch.
> 
> [d69a61d](https://github.com/sugarlabs/fototoon-activity/commit/d69a61d43dc26981d1ef1b0ad5e193422aca1b0d) does work with Python 2.
> 
> But when I began to test [d69a61d](https://github.com/sugarlabs/fototoon-activity/commit/d69a61d43dc26981d1ef1b0ad5e193422aca1b0d) on Python 3, it instantly failed. The failure suggests you haven't tested. Please test before commit.
> 
> The actual failure relates to [Check for use of Gtk.CssProvider, and if so ensure the load_from_data function is given bytes rather than unicode strings](https://github.com/sugarlabs/sugar-docs/blob/master/src/python-porting-guide.md#how-to-port-an-activity-to-python-3).

I didn't get any errors when I tested the first time but I've been able to reproduce the error you got, fixed in 650ad08.

**Comment by quozl** [comment]
Thanks.  Perhaps you missed [Make Sugar Home View reload the bundle; by restarting Sugar or moving the bundle directory out of ~/Activities and back again a few seconds later,](https://github.com/sugarlabs/sugar-docs/blob/master/src/python-porting-guide.md#how-to-port-an-activity-to-python-3).  Without this, Sugar will continue to start the activity using the cached value of _exec_ in the _activity.info_ file.

Tested on Ubuntu 19.04 Disco.  Save as PDF did not work, logs have;

```log
Traceback (most recent call last):
  File "/usr/share/sugar/activities/FotoToon.activity/historietaactivity.py", line 430, in _save_as_pdf
    context.show_page()
historietaactivity.IOError: error while writing to output stream
```

**Comment by chimosky** [comment]
For some reason the `RawObject` is deleted and it seems it happens as soon as it's created. 
The only call that leads to the `RawObject` being called is when an image is added. 
I'm yet to find out why it gets deleted, L241 of `toolbar.py` shows a created hardlink which links the `RawObject` to the `tempfile` and even if the `RawObject` is deleted, `tempfile` still exists so I'm wondering why the reference to the `RawObject`. 

```
1574943117.527407 WARNING root: RawObject was deleted without cleaning up. Call RawObject.destroy() before disposing it.
```

**Comment by quozl** [comment]
Interesting, thanks.  I have not seen that.  What sequence to reproduce?

**Comment by chimosky** [comment]
**Steps to reproduce**

- Start activity.
- Add any image.
- Save to pdf and quit activity.

Logs show `logging warnings` - *which should be debug* - from `add_image` of `toolbar.py` and the error above too.

**Comment by quozl** [comment]
Retested using your steps, bb816e0a0b2dcf0e8d41c351649dad6cb9d35fa0 on Ubuntu 19.04 with Sugar 0.116.  I do not get RawObject warning at all.  I do get this;

```log
1575063978.052097 ERROR root: ObjectChooser: <sugar3.datastore.datastore.DSObject object at 0x7f542e409d30>
1575063978.056600 ERROR root: imagen seleccionada: /home/guest/.sugar/default/data/53d778a5-19ea-41d7-939c-0b1b6d50a85c_v2k_4pq7.png
1575063978.057606 ERROR root: tempfile_name: /home/guest/.sugar/default/org.eq.FotoToon/instance/tmp1575063978
1575063978.058565 ERROR root: seting image_name /home/guest/.sugar/default/org.eq.FotoToon/instance/tmp1575063978
Traceback (most recent call last):
  File "/usr/share/sugar/activities/FotoToon.activity/historietaactivity.py", line 430, in _save_as_pdf
    context.show_page()
historietaactivity.IOError: error while writing to output stream
```

**Comment by chimosky** [comment]
This is what I get, can't think of why you get something a bit different.

```
1574943117.527407 WARNING root: RawObject was deleted without cleaning up. Call RawObject.destroy() before disposing it.
1574943117.527790 ERROR root: ObjectChooser: <sugar3.datastore.datastore.RawObject object at 0x7f87f15274a8>
1574943117.529040 ERROR root: imagen seleccionada: /home/ibiam/.sugar/default/data/rawobjecthxekrw2j
1574943117.554590 ERROR root: tempfile_name: /home/ibiam/.sugar/default/org.eq.FotoToon/instance/tmp1574943117
1574943117.555905 ERROR root: seting image_name /home/ibiam/.sugar/default/org.eq.FotoToon/instance/tmp1574943117
1574943117.557609 WARNING root: RawObject was deleted without cleaning up. Call RawObject.destroy() before disposing it.
Traceback (most recent call last):
  File "/home/ibiam/Activities/fototoon-activity/historietaactivity.py", line 431, in _save_as_pdf
    context.show_page()
historietaactivity.IOError: error while writing to output stream
```

**Comment by quozl** [comment]
> This is what I get, can't think of why you get something a bit different.
> ```
>   File "/home/ibiam/Activities/fototoon-activity/historietaactivity.py", line 431, in _save_as_pdf
>     context.show_page()
> historietaactivity.IOError: error while writing to output stream
> ```

Well, you're not using the same source code as I am.  Line 431 in your traceback is different to what you have pushed.

https://github.com/sugarlabs/fototoon-activity/blob/bb816e0a0b2dcf0e8d41c351649dad6cb9d35fa0/historietaactivity.py#L431 

Ignoring that, the remaining difference is the message about RawObject, which comes from the toolkit, so my guess is that we have different versions of the toolkit.  What toolkit source version are you using?

**Comment by chimosky** [comment]
> Well, you're not using the same source code as I am. Line 431 in your traceback is different to what you have pushed.

I had a print statement that's why the extra line.

> Ignoring that, the remaining difference is the message about RawObject, which comes from the toolkit, so my guess is that we have different versions of the toolkit. What toolkit source version are you using?

I'm using version 0.116 HEAD at https://github.com/sugarlabs/sugar-toolkit-gtk3/commit/e41c3a5f35ae796625e28beb6c30d91158120794.

**Comment by quozl** [comment]
Regarding the _IOError: error while writing to output stream_, this is important to fix, and is caused by the Cairo PDFSurface being unable to write to a Python 3 text file.  When this is changed to a binary file, it works.

Regarding the _RawObject was deleted without cleaning up_, this is not necessarily important if it doesn't cause any symptom.  I recall release notes of Python mentioning changes to object deletion timing.  I guess you have a different version of Python.  I'm using 3.7.3.  If I could reproduce it, then I would use _pdb_ or iterate on adding tracebacks to [RawObject](https://github.com/sugarlabs/sugar-toolkit-gtk3/blob/master/src/sugar3/datastore/datastore.py#L231).  Tracebacks could tell you **when** the objects are being created.  Or do a static analysis; I've looked briefly at the activity source code, and the datastore functions are used directly in a couple of places.  Make sure the objects destroy method is called before they are implicitly deleted.

**Comment by chimosky** [comment]
> Regarding the _IOError: error while writing to output stream_, this is important to fix, and is caused by the Cairo PDFSurface being unable to write to a Python 3 text file. When this is changed to a binary file, it works.

Okay, thanks.
> 
> Regarding the _RawObject was deleted without cleaning up_, this is not necessarily important if it doesn't cause any symptom. I recall release notes of Python mentioning changes to object deletion timing. I guess you have a different version of Python. I'm using 3.7.3. If I could reproduce it, then I would use _pdb_ or iterate on adding tracebacks to [RawObject](https://github.com/sugarlabs/sugar-toolkit-gtk3/blob/master/src/sugar3/datastore/datastore.py#L231). Tracebacks could tell you **when** the objects are being created. Or do a static analysis; I've looked briefly at the activity source code, and the datastore functions are used directly in a couple of places. Make sure the objects destroy method is called before they are implicitly deleted.

I'm using version 3.7.3 too, the `RawObject` that wasn't cleaned up was the one used in logging and destroying it at that point yielded none being printed in the logs so I removed it as it wasn't informative.

**Comment by quozl** [comment]
Thanks.  Tested.  Reviewed.

**Pull request merged**
